Fine tuning the libraryPageStart branch
LEIC-ES-2021-22/3LEIC03T1 pull request #20
Opened 2022-04-12 18:44 UTC by monkin77

2022-04-12 18:57 UTC, monkin77 commented
TO-DO:

- [ ] Find why the TextInput is unfocusing instantly

2022-04-19 07:58 UTC, BrunoRosendo requested changes

2022-04-19 07:58 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_search_header.dart
> +            controller: searchController, // TODO Fix page refreshing on focus
```suggestion
            controller: searchController,
```

2022-04-19 08:22 UTC, BrunoRosendo approved these changes

2022-04-19 08:23 UTC, merged