Feature/book details
LEIC-ES-2021-22/3LEIC03T1 pull request #24
Opened 2022-04-27 17:39 UTC by monkin77

2022-05-04 20:06 UTC, BrunoRosendo commented
Please add .idea/ to .gitignore and remove it from the repo

2022-05-04 21:12 UTC, BrunoRosendo requested changes
Good job! This is already looking pretty good. I left some suggestions and questions

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +  }
Do we need StoreConnector here? I think it should be enough to use the book being passed in the constructor. The `getBody` could just become the `build` from `BookDetailsWidget`

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_container.dart
> +                              ),
The `Hero` here looks great!

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                ),
Looking at our mockup, I feel like the download button is too large and corny (not round like in the mockup), and the reserve button could be bigger. What do you think?

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +    }
I think we should tell how many units are available even if we don't know the total. For example `5 unidades disponíveis` without the `/X`

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      this.book.language = "unknown";
Do you guys think we should display `unknown` here or just simply not display anything? @monkin77 @ruialves35  @laureansvictor

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                        color: Colors.black,
This arrow looks nice but shouldn't we use the default back button from the app? We hadn't considered this in the mockup but I feel like it makes more sence
![untitled](https://user-images.githubusercontent.com/55768934/166819662-6ff7c307-e0dc-477c-a18a-3e85f057c12c.png)

The sandwish should be the back arrow in this example. There are other places in the app where this logic is used

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                ),
In my phone, the language is too far into the right.. We shouldn't hard code the distance in pixels like this.
In Flutter, we have structures similar to CSS's align, flex, etc. which we can use for this type of things

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                ),
Can you please fix this case and look if there are other places where it's better to use alignments instead of sizedBox?

2022-05-04 21:12 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      themes.add(Text("Não há temas"));
Same thing here. Should we say there are no themes or not display anything? I'm not sure about this one

2022-05-05 10:50 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      this.book.language = "unknown";
I'm not sure, since the design could be weird with an empty space on certain fields. But if we are writing anything we should keep it in Portuguese "desconhecido"

2022-05-05 10:51 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                        color: Colors.black,
I agree. I think it's cleaner that way

2022-05-05 10:51 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      themes.add(Text("Não há temas"));
Maybe we could see how it is with / without when we do a meeting and choose accordingly

2022-05-08 18:34 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                },
You can put a URL in the mocks and implement this already

2022-05-09 18:49 UTC, victorsnunes commented on src/app_feup/lib/view/Widgets/book_container.dart
> +                              ),
Thanks!

> The `Hero` here looks great!

2022-05-09 18:51 UTC, victorsnunes commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                ),
> Looking at our mockup, I feel like the download button is too large and corny (not round like in the mockup), and the reserve button could be bigger. What do you think?

I agree, I just haven't found an easy way to solve this problem hahah

2022-05-09 18:54 UTC, victorsnunes commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +    }
> I think we should tell how many units are available even if we don't know the total. For example `5 unidades disponíveis` without the `/X`

I agree, it would look more clean and simple. I just did it this way to follow our original mockup

2022-05-18 15:59 UTC, monkin77 reviewed
The page is looking good! However, when I'm running on my phone it has an error: "Right overflow by 15 pixels".

2022-05-18 15:59 UTC, monkin77 commented on .idea/ESOF.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you remove these .idea files from the branch and add them .idea folder to the gitignore?

2022-05-18 15:59 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      this.book.releaseYear = "desconhecido";
After looking at it, I think it looks nicer if we don't show the fields that we don't know about, instead of saying "desconhecido". For example, in the language

2022-05-18 15:59 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +          height: 200.0,
Whenever we set containers with absolute values of width/height, we should use the utilitary methods `hs` and `vs` (horizontal / vertical scaling). This is used to make sure the containers grow according to the screen size.

2022-05-18 15:59 UTC, monkin77 commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                    width: 100,
I think this width and height could also use the utilitary methods I mentioned above. These methods are located at: src\app_feup\lib\utils\methods.dart

2022-05-18 15:59 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_container.dart
> +            )));
Don't forget to rebase with the latest changes from master. This book_container has been also changed and is updated on the master branch. Basically, we moved the common code to a GenetricLibraryContainer and the BookContainer is extending it.

2022-05-23 13:41 UTC, BrunoRosendo requested changes
@laureansvictor Please check the comments in this PR and change your commits in a way that it tells a linear "story". I explained this better in your other PR but we can also help you with that

2022-05-23 13:41 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +*/
Remove the comment if it's not being used

2022-05-23 13:41 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +      themes.add(Text('Não há temas'));
```suggestion
      themes.add(Text('Não existem temas disponíveis'));
```

2022-05-23 13:51 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +                },
The iteration is ending so let's leave this to the next one

2022-05-23 14:51 UTC, laureansvictor commented
> @BrunoRosendo 

Too many victors in this groups haha i think you meant the other PR from @victorsnunes , probably the one related to the reservation forms.

Basically it's to try and squash the commits ?

2022-05-23 17:35 UTC, monkin77 reviewed
I think this is good to go! We should allocate some time to improve some details later on. For example, the language in the book details page is shown by their initials: 'eng' which is not very natural.

2022-05-23 17:35 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_container.dart
> +enum BookContainerType { searchResult, reservation }
This can be removed

2022-05-23 18:29 UTC, BrunoRosendo approved these changes

2022-05-23 18:29 UTC, merged