Search book scrapper
LEIC-ES-2021-22/3LEIC03T1 pull request #25
Opened 2022-04-27 19:19 UTC by ruialves35

2022-05-03 14:57 UTC, laureansvictor approved these changes
The parsing function so far is working, now we need to focus into login and saving the cookie.

2022-05-05 02:10 UTC, BrunoRosendo requested changes
This is looking really good! Left some suggestions and questions

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/library.dart
> +    'https://catalogo.up.pt/F/?func=find-b&request=Design+Patterns';
Is this being used?

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/library.dart
> +    // cookie just works if we get it from the base URL for some reason.
```suggestion
    // cookie only works if we get it from the base URL
```

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/library.dart
> +      return Future.error('Library Books request failed');
Maybe say in the error that the request was forbidden

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +    };
You can create a dynamic map in Dart. It's probably useful here
https://vitalflux.com/flutter-map-string-dynamic-code-example/

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +      // Second <td> has it's value, the language, year, editor's name ...
```suggestion
      // Second <td> has its value, the language, year, editor's name ...
```

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +                  .firstChild // <img with src
```suggestion
                  .firstChild // <img> with src
```

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +      final String digitalURL = digitalInfoHtml != ''
```suggestion
      final String digitalURL = hasDigitalVersion
```

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
Is the `/` before `$book` supposed to be missing?

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
Maybe this condition should use `totalUnits`? I think it'd make sense to tell the user that the book exists physically and that no units are available

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/model/app_state.dart
> +      'books': <Book>[],
```suggestion
      'searchBooks': <Book>[],
```
In order to be consistent with the other PRs

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/redux/action_creators.dart
> +          await extractBooks(store, library, 'Design Patterns');
Is the idea here to use whatever the user has written on the search bar instead of 'Design Patterns'?

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/redux/action_creators.dart
> +          await extractBooks(store, library, 'Design Patterns');
Also, why does this work without setting the user's faculty? i didn't catch that

2022-05-05 02:10 UTC, BrunoRosendo commented on src/app_feup/lib/redux/reducers.dart
> +
Was this supposed to change?

2022-05-05 07:33 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/library.dart
> +    'https://catalogo.up.pt/F/?func=find-b&request=Design+Patterns';
nop, i'm gonna remove it

2022-05-05 07:35 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +    };
that's perfect, i didn't know about that, thanks :D

2022-05-05 07:43 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
Ah so hasPhysicalVersion would just be "exists a physical version even it's not available"?

2022-05-05 07:46 UTC, ruialves35 commented on src/app_feup/lib/redux/action_creators.dart
> +          await extractBooks(store, library, 'Design Patterns');
Yep, it's supposed to get the user search. It works because the catalog.up.pt also works without a login, this is just the search on catalog website

2022-05-05 07:48 UTC, ruialves35 commented on src/app_feup/lib/redux/reducers.dart
> +
I don't think it changed, i just moved the place of it so i could have the books functions closer to exams functions

2022-05-05 08:18 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
the parser already gets the / but do you think it's better to have it in the function and take it out of the parser?

2022-05-05 13:22 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
Only if it's an easy fix

2022-05-05 13:22 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
I think so

2022-05-05 13:50 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
I think it is, i'll fix it today

2022-05-05 13:50 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
Ok looks good, then the logic about reservation will take care of the unitsAvailable right?

2022-05-05 14:01 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
I didn't understand the question.
But we can probably use something like `hasPhysicalVersion: totalUnits > 0 || unitsAvailable > 0`, just in case the information isn't complete in catalogo

2022-05-05 14:17 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
After checking i don't think that's worth since I'm just parsing for .elementAt(catalogImgPathIdx).firstChild.firstChild.attributes['src'] and I would have to get the substring. Since we are already receiving the string parsed, I'll leave it like this

2022-05-05 14:21 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +String catalogBookUrl(String book) => 'https://catalogo.up.pt$book';
Sounds good

2022-05-05 14:25 UTC, BrunoRosendo requested changes

2022-05-05 14:25 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: totalUnits > 0 ? true : false,
Check my other comment regarding this please

2022-05-05 15:16 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: unitsAvailable > 0 ? true : false,
looks perfect. I found a mistake on my code, i'll change it as re-ask for a review. I'll make it this way, totalUnits > 0 || unitsAvailable > 0 because I didn't understand yet the catalogo information of the 1/0 or 0/1

2022-05-05 15:27 UTC, ruialves35 commented on src/app_feup/lib/controller/library_interface/parser_library.dart
> +        hasPhysicalVersion: totalUnits > 0 ? true : false,
i think the other approach is good, i'll do it that way

2022-05-09 18:48 UTC, BrunoRosendo approved these changes

2022-05-09 18:49 UTC, merged