Feature/reservations page
LEIC-ES-2021-22/3LEIC03T1 pull request #32
Opened 2022-05-07 14:42 UTC by monkin77

2022-05-07 15:06 UTC, ruialves35 approved these changes

2022-05-07 15:50 UTC, BrunoRosendo requested changes
Great job! The page looks really good.
I left some suggestions related to code. It's missing the tests but we can do that in another PR

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  });
What if the BookReservation has a Book object instead of repeating everything again?

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  }
The Book method could be used here

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/model/entities/book_reservation.dart
> +}
And here you could also reuse the Book's methods, i.e., `book.hashcode ^ reservationNumber.hashCode` and so on

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/model/utils/reservation_status.dart
> +}
If we don't need it for now then we'll probably never need it. I'd say remove it

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_container.dart
> +  }
```suggestion
  Widget buildLibraryContainerBody(BuildContext context);
```
I think this makes it abstract. No need to instantiate, right?

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                      Navigator.pop(context);
This will get tricky. If we push a new page instead of popping, what happens if we navigate back and forth between the library and reservations pages? It'll probably stack all the pages and the back button will become unusable.
However, it doesn't make sense to use pop() here because we'll be able to navigate to this page from the personal area. Is it possible to make some kind of logic that tells us if we should pop or push?

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_container.dart
> +}
Should this be here or in book_container.dart ?

2022-05-07 15:50 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_container.dart
> +abstract class LibraryContainer extends StatelessWidget {
Imo BookContainer and LibraryContainer are easy to mix up. I'd say rename this to something like `GenericLibraryContainer` or something like that, but I'll leave it up to you

2022-05-07 15:55 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                      Navigator.pop(context);
Honestly the UX as it is with pop is not bad. At least from what I've used. However, in React there's a 'navigate' feature instead of push that navigates to the page if it exists in the stack. If it does not, it then pushes. That would be the ideal behavior I guess

2022-05-07 15:55 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/library_container.dart
> +}
I forgot to move this one xD

2022-05-07 15:57 UTC, monkin77 commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  });
I thought about that, but the reservation does not contain all the info about the book. That's why I left it this way until we have the scrapper to get this info. IT was for that reason that I also created a Book constructor that receives a reservation

2022-05-07 16:00 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                      Navigator.pop(context);
But I haven't looked for it for too long since the behavior right now was okay in my view.

2022-05-07 16:04 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                      Navigator.pop(context);
Tha behavior would be perfect. Right now this works well but won't work when we have a shortcut for the reservations in the personal area

2022-05-07 16:06 UTC, BrunoRosendo commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  });
I see that but why is it a problem? Is there a problem to leaving some book fields undefined?

2022-05-07 16:14 UTC, monkin77 commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  });
I'm not sure. I don't know if methods like this one will throw an error if undefined
![image](https://user-images.githubusercontent.com/28673635/167262674-0336f624-4b26-4af8-b259-9a9ce4c5eb99.png)
But it was more because, from what I saw, there are only 2-3 fields of the Book model that we will actually have, which would leave most of the things null. I just haven't removed them from the reservation.

2022-05-07 16:49 UTC, ruialves35 commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  });
that's a nice point, if the fields are undefined do hash code fails? 
Well it would be easier to understand what book we are getting on the reservation if we pass all the book, even if it doesn't use all the fields

2022-05-08 18:18 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                      Navigator.pop(context);
https://api.flutter.dev/flutter/widgets/Navigator/pushReplacement.html

2022-05-08 18:19 UTC, BrunoRosendo commented on src/app_feup/lib/model/entities/book_reservation.dart
> +  }
Remove I guess

2022-05-08 18:31 UTC, BrunoRosendo commented
Ask the teacher about unit tests

2022-05-09 19:01 UTC, BrunoRosendo approved these changes
To the moon 🚀

2022-05-09 19:04 UTC, ruialves35 approved these changes

2022-05-09 19:06 UTC, merged