Feature/book reservation form
LEIC-ES-2021-22/3LEIC03T1 pull request #47
Opened 2022-05-17 09:05 UTC by victorsnunes

Implements book reservation form in #2

2022-05-17 09:20 UTC, BrunoRosendo requested changes
This is looking pretty good. I left some comments

Apart from that, please try to squash the commits in the way that the commit history is more readable and effectively tells us what was implemented in this task (telling a story, like the teacher said).
You can do this by using `git rebase -i <commit>` where commit is the hash of the last commit you want to mantain. When done, you need `git push --force-with-lease` to update this PR

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +          print("Date is not selected");
Are these prints supposed to be here?

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +        }
Same thing with the prints

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +
Same thing with the prints

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              _formKey.currentState.save();
What does this `save` do? I'm curious, as I didn't use it in other forms

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
We should maybe have 2 buttons (submit and cancel), the same way we have in the [mockup](https://github.com/LEIC-ES-2021-22/3LEIC03T1/issues/2) and in the [search filters](https://github.com/LEIC-ES-2021-22/3LEIC03T1/blob/2d0551d5bf4582b6c60e154ad749426f79fd7868/src/app_feup/lib/view/Widgets/search_filter_form.dart#L78)

The elevated button is the one with the red background

2022-05-17 09:20 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
Also, we should have it in portuguese, since the app is all the in portuguese

2022-05-18 20:55 UTC, victorsnunes commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              _formKey.currentState.save();
Good question hahah

2022-05-18 20:57 UTC, victorsnunes commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
Right, I'll do it

2022-05-19 09:04 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              _formKey.currentState.save();
I think it's supposed to save the form? Can you check if the state is reset after you re-open the dialog? I'm afraid the state will persist after we close it

2022-05-24 21:36 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
This is not changed yet

2022-05-24 22:29 UTC, BrunoRosendo commented
@victorsnunes Please start marking the comments as resolved when you solve them, it becomes much easier to manage. Also, please look at what I wrote about the commits and the rebase. If you want, we can help you with that

2022-05-27 14:43 UTC, ruialves35 commented
Any improvement on this task? As @BrunoRosendo said, don't forget to close the comments that you already solved @victorsnunes , it's much easier to check the development of this

2022-05-30 22:39 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
@BrunoRosendo something like that?

![Screenshot from 2022-05-30 23-37-34](https://user-images.githubusercontent.com/9393719/171065229-e21f9b23-ffb1-496d-ba35-8d629cd382e2.png)

2022-05-30 22:39 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              _formKey.currentState.save();
@BrunoRosendo  @victorsnunes  was this fixed?

2022-05-31 06:52 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              _formKey.currentState.save();
I think só. Its working as intended

2022-05-31 06:54 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/book_reservation_dialog.dart
> +              }
Yes! But please be consistent with other pages and:
- Put the cancel on the left
- Change the submit button to the app's main theme (please see search filters for reference)
- Change the button texts to Portuguese

2022-06-03 00:07 UTC, BrunoRosendo commented
Just missing a rebase I think?

2022-06-03 10:57 UTC, victorsnunes commented
> Just missing a rebase I think?
I merged the master on this branch, and it says it's already up to date.

2022-06-05 00:54 UTC, BrunoRosendo approved these changes

2022-06-05 01:01 UTC, merged