Reservation details page
LEIC-ES-2021-22/3LEIC03T1 pull request #49
Opened 2022-05-18 11:19 UTC by laureansvictor

Agora do catálogo podemos ir direto para os livros reservados e destes ao clicar em algum livro, teremos as informações daquela reserva em específico:

![Screenshot from 2022-05-18 12-34-51](https://user-images.githubusercontent.com/9393719/169029666-2cef9382-5147-4d34-b1b1-cfb67cc4db62.png)

2022-05-18 18:43 UTC, monkin77 requested changes
Great progress! 🚀 I left some suggestions for things that we could improve

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +  // ignore: lines_longer_than_80_chars
We should avoid this. Let's keep all lines not longer than 80 😛

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +  // ignore: lines_longer_than_80_chars
Same thing as above

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +          height: 200.0,
Whenever we set containers with absolute values of width/height, we should use the utilitary methods hs and vs (horizontal / vertical scaling). This is used to make sure the containers grow according to the screen size.

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +        Padding(
A comment not related with this line, but in my phone the elements are too big, causing it to overflow right by 369 pixels.  You can see it in the screenshot below
![WhatsApp Image 2022-05-18 at 7 33 42 PM](https://user-images.githubusercontent.com/28673635/169119382-d2b5ec5d-ee29-4e1f-a002-3332b22f4103.jpeg)

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/library_reservations_header.dart
> +                  // ignore: lines_longer_than_80_chars
Same comment about lines with more than 80 chars

2022-05-18 18:43 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/reservation_container.dart
> +            child: InkWell(
Is this build the same as the one in generic_library_container, except that when clicked it navigates to another page? I believe that is the case and the same thing happens with the book_container. I feel like it's a waste to declare the whole build function just because of the onTap event being different.
What do you think about adding an additional method to the generic_library_container `onClick` that will need to be overridden by the child classes `ReservationContainer` and `BookContainer`? This way, that additional method will take care of the navigation and we make this cleaner.

2022-05-18 22:12 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/reservation_container.dart
> +            child: InkWell(
Looking into it.

2022-05-18 22:49 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +        Padding(
Now i'm using the hs and vs functions, also decreased the size of basically everything.
Whenever you have time check this again please.

2022-05-18 22:52 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/reservation_container.dart
> +            child: InkWell(
@monkin77  will this function be called inside the generic_library_container ?
If not i think this could be applied in an improvement phase.
I think we have the same problem with book details.

2022-05-19 09:01 UTC, BrunoRosendo commented on src/app_feup/lib/view/Widgets/reservation_container.dart
> +            child: InkWell(
@laureansvictor It shouldn't take very long to change this, so I think we should do it now, no reason to wait. The generic_library_container is an abstract class which you can extend and then you just need to override a method or two, like @monkin77  is saying

2022-05-20 11:10 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_reservation_details.dart
> +        Padding(
While it did reduce the size of things, it is still too big. I think it would be better if you could run the App on your phone and adjust the sizes accordingly. 

![WhatsApp Image 2022-05-20 at 12 07 59 PM](https://user-images.githubusercontent.com/28673635/169515801-fbb00050-22dd-496b-9f98-b93b952df870.jpeg)

2022-05-20 18:30 UTC, laureansvictor commented on src/app_feup/lib/view/Widgets/reservation_container.dart
> +            child: InkWell(
Done \o We are overrigind onClick function now.

2022-05-20 19:05 UTC, monkin77 requested changes

2022-05-20 19:05 UTC, monkin77 commented on src/app_feup/analysis_options.yaml
> -    asset_directory_does_not_exist: ignore
We should avoid changing the analysis settings since we are working on top of a project with settings already defined

2022-05-20 19:05 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_container.dart
> +  InkWell onClick(BuildContext context){
This onClick is missing

2022-05-20 19:10 UTC, monkin77 commented on src/app_feup/lib/view/Widgets/book_container.dart
> +  InkWell onClick(BuildContext context){
Will be done in the Book Details Merge request

2022-05-20 20:53 UTC, monkin77 approved these changes

2022-05-20 20:53 UTC, merged