Store/aleph cookie
LEIC-ES-2021-22/3LEIC03T1 pull request #61
Opened 2022-05-24 15:23 UTC by ruialves35

2022-05-24 21:30 UTC, BrunoRosendo requested changes

2022-05-24 21:30 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library/library.dart
> +import 'package:uni/redux/actions.dart';
Why is this necessary?

2022-05-24 21:30 UTC, BrunoRosendo commented on src/app_feup/pubspec.yaml
> +  # Cookies
```suggestion
```
I think it's self explanatory

2022-05-25 13:31 UTC, ruialves35 commented on src/app_feup/lib/controller/library/library.dart
> +import 'package:uni/redux/actions.dart';
To create object of class Store in Library. I couldn't find out how to use the store and dispatch without being this way :(

2022-05-25 17:54 UTC, BrunoRosendo requested changes

2022-05-25 17:54 UTC, BrunoRosendo commented on src/app_feup/lib/controller/library/library.dart
> +import 'package:redux/src/store.dart';
```suggestion
import 'package:redux/redux.dart';
```
This solved it. You were trying to import from a private package instead of a public one. You can read about it here https://stackoverflow.com/questions/52925209/error-dont-import-implementation-files-from-another-package

2022-05-25 17:54 UTC, BrunoRosendo commented on src/app_feup/lib/redux/actions.dart
> +}
Is this action not in the reducers.dart file? I could be wrong but it feels like something is missing or not being used

2022-05-26 10:04 UTC, BrunoRosendo approved these changes

2022-05-26 10:08 UTC, merged