Feature/digital version
LEIC-ES-2021-22/3LEIC03T1 pull request #70
Opened 2022-05-31 09:09 UTC by victorsnunes

2022-06-02 23:39 UTC, BrunoRosendo requested changes
It's working as expected but the PR needs a rebase, we can help you with that

2022-06-02 23:39 UTC, BrunoRosendo commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +              }*/
It worked on my phone. Choose what you think fits best

2022-06-03 10:46 UTC, victorsnunes commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +              }*/
Okay. I chose to remove the comment and open without a verification (I think is secure because it's just a website and every smartphone can launch it).

2022-06-03 10:47 UTC, victorsnunes commented on src/app_feup/lib/view/Pages/book_details_page_view.dart
> +              }*/
I pulled the master and merged to this branch. It's up to date.

2022-06-05 00:20 UTC, BrunoRosendo approved these changes

2022-06-05 00:26 UTC, merged